#!/bin/bash

com4_path="$( dirname $( readlink -f "$0" ))"
title="CommonJS unit tests"
path="`pwd`";
html="$path/../test/index.html"

. "$com4_path/include.sh"

rm -r "$path/../test/js/"
mkdir "$path/../test/js/"

cd ../../commonjs/tests/

echo "<html><head><title>$title</title>
<style>body{font:12px sans-serif;}</style><script>
function print(text) { document.write('<p>'+text+'</p>'); }
</script></head><body>
<h1>$title</h1>" > "$html"

for dir in modules/1.0/*; do

  js="js/`basename "$dir"`.js"
  `cd $dir; com4 -i program -o $path/../test/$js`
  echo "<h2><a href="$js">$dir</a></h2><script src=\"$js\"></script>" >> "$html"

done

echo "</body></html>" >> "$html"
